### ISSUE TITLE
Importing vla112f.mlx issue.

### ISSUE THREAD

**Issue by zeek2500** [gomtuu/import_valkyria#10]
This error comes up when I attempt to import filename vla112f.mlx from DLC_005_EN

[ConsoleError.txt](https://github.com/gomtuu/import_valkyria/files/3307074/ConsoleError.txt)

```
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\__init__.py", line 914, in execute
    self.import_file(self.filepath)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\__init__.py", line 903, in import_file
    self.valk_scene.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\__init__.py", line 849, in read_data
    self.source_file.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\__init__.py", line 164, in read_data
    shape_key_set.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\__init__.py", line 430, in read_data
    self.F.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\valkyria\files.py", line 255, in read_data
    kfsh.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\valkyria\files.py", line 266, in read_data
    kfss.read_data()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\valkyria\files.py", line 402, in read_data
    self.read_vertex_formats()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\import_valkyria\valkyria\files.py", line 353, in read_vertex_formats
    assert vertfmt['bytes_per_vertex'] in [0x0, 0x8, 0xc, 0x14, 0x18, 0x1c]
AssertionError

location: <unknown location>:-1

```

**Comment by gomtuu** [comment]
Thanks for the bug report! I'll take a look.

**Comment by CidulFaust** [comment]
Hi, got the same error with the same model. Was the error able to be patched?
